apps/detector/models.py
from datetime import datetime

from apps.app import db


class UserImage(db.Model):
    __tablename__ = "user_images"
    id = db.Column(db.Integer, primary_key=True)
    # user_idはusersテーブルのidカラムを外部キーとして設定する
    user_id = db.Column(db.String, db.ForeignKey("users.id"))
    image_path = db.Column(db.String)
    is_detected = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)


class UserImageTag(db.Model):
    # テーブル名を指定する
    __tablename__ = "user_image_tags"
    id = db.Column(db.Integer, primary_key=True)
    # user_image_idはuser_imagesテーブルのidカラムの外部キーとして設定する
    user_image_id = db.Column(db.String, db.ForeignKey("user_images.id"))
    tag_name = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

apps/detector/forms.py
from flask_wtf.file import FileAllowed, FileField, FileRequired
from flask_wtf.form import FlaskForm
from wtforms.fields.simple import SubmitField


class UploadImageForm(FlaskForm):
    # ファイルフィールドに必要なバリデーションを設定する
    image = FileField(
        validators=[
            FileRequired("画像ファイルを指定してください。"),
            FileAllowed(["png", "jpg", "jpeg"], "サポートされていない画像形式です。"),
        ]
    )
    submit = SubmitField("アップロード")


class DeleteForm(FlaskForm):
    submit = SubmitField("削除")

apps/detector/__init__.py
import apps.detector.models

apps/detector/views.py
import uuid
from pathlib import Path
from apps.app import db
from apps.crud.models import User
from apps.detector.models import UserImage, UserImageTag
from apps.detector.forms import UploadImageForm, DeleteForm
from flask import (
    Blueprint,
    render_template,
    current_app,
    send_from_directory,
    redirect,
    url_for,
    flash,
    request,
)
from flask_login import current_user, login_required

dt = Blueprint("detector", __name__, template_folder="templates")


@dt.route("/")
def index():
    user_images = (
        db.session.query(User, UserImage)
        .join(UserImage)
        .filter(User.id == UserImage.user_id)
        .all()
    )

    delete_form = DeleteForm()

    return render_template(
        "detector/index.html", user_images=user_images, delete_form=delete_form
    )


@dt.route("/images/<path:filename>")
def image_file(filename):
    return send_from_directory(current_app.config["UPLOAD_FOLDER"], filename)


@dt.route("/upload", methods=["GET", "POST"])
# ログイン必須とする
@login_required
def upload_image():
    # UploadImageFormを利用してバリデーションをする
    form = UploadImageForm()
    if form.validate_on_submit():
        # アップロードされた画像ファイルを取得する
        file = form.image.data

        # ファイルのファイル名と拡張子を取得し、ファイル名をuuidに変換する
        ext = Path(file.filename).suffix
        image_uuid_file_name = str(uuid.uuid4()) + ext

        # 画像を保存する
        image_path = Path(current_app.config["UPLOAD_FOLDER"], image_uuid_file_name)
        file.save(image_path)

        # DBに保存する
        user_image = UserImage(user_id=current_user.id, image_path=image_uuid_file_name)
        db.session.add(user_image)
        db.session.commit()

        return redirect(url_for("detector.index"))
    return render_template("detector/upload.html", form=form)


@dt.route("/images/delete/<string:image_id>", methods=["POST"])
@login_required
def delete_image(image_id):
    try:
        # user_image_tagsテーブルからレコードを削除する
        db.session.query(UserImageTag).filter(
            UserImageTag.user_image_id == image_id
        ).delete()

        # user_imageテーブルからレコードを削除する
        db.session.query(UserImage).filter(UserImage.id == image_id).delete()

        db.session.commit()
    except Exception as e:
        flash("画像削除処理でエラーが発生しました。")
        # エラーログ出力
        current_app.logger.error(e)
        db.session.rollback()
    return redirect(url_for("detector.index"))


@dt.route("/images/search", methods=["GET"])
def search():
    # 画像一覧を取得する
    user_images = db.session.query(User, UserImage).join(
        UserImage, User.id == UserImage.user_id
    )

    # GETパラメータから検索ワードを取得する
    search_text = request.args.get("search")

    user_image_tag_dict = {}
    filtered_user_images = []

    # user_imagesをループしuser_imagesに紐づくタグ情報を検索する
    for user_image in user_images:
        # 検索ワードが空の場合はすべてのタグを取得する
        if not search_text:
            # タグ一覧を取得する
            user_image_tags = (
                db.session.query(UserImageTag)
                .filter(UserImageTag.user_image_id == user_image.UserImage.id)
                .all()
            )
        else:
            # 検索ワードで絞り込んだタグを取得する
            user_image_tags = (
                db.session.query(UserImageTag)
                .filter(UserImageTag.user_image_id == user_image.UserImage.id)
                .filter(UserImageTag.tag_name.like("%" + search_text + "%"))
                .all()
            )

            # タグが見つからなかったら画像を返さない
            if not user_image_tags:
                continue

            # タグがある場合はタグ情報を取得しなおす
            user_image_tags = (
                db.session.query(UserImageTag)
                .filter(UserImageTag.user_image_id == user_image.UserImage.id)
                .all()
            )

        # user_image_id をキーとする辞書にタグ情報をセットする
        user_image_tag_dict[user_image.UserImage.id] = user_image_tags

        # 絞り込み結果のuser_image情報を配列セットする
        filtered_user_images.append(user_image)

    delete_form = DeleteForm()

    return render_template(
        "detector/index.html",
        # 絞り込んだuser_images配列を渡す
        user_images=filtered_user_images,
        # 画像に紐づくタグ一覧の辞書を渡す
        user_image_tag_dict=user_image_tag_dict,
        delete_form=delete_form,
    )


@dt.errorhandler(404)
def page_not_found(e):
    return render_template("detector/404.html"), 404


2

apps/detector/templates/detector/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <title>detector</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" /> 
    <!-- 後から読み込んだファイルが優先されるので書き足したり訂正する場合に用いる -->
</head>

<body>
    <!-- ナビゲーションバーを作成する -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">　
        <div class="container">
            <a class="navbar-brand " href="{{ url_for('detector.index') }}">detector</a>
            <!-- 画像検索フォームを追加する -->
            {% if url_for(request.endpoint) == url_for('detector.index') or
            url_for(request.endpoint) == url_for('detector.search') %}
            <div class="btn-group">
                <form method="GET" action="{{ url_for('detector.search') }}" name="dtSearchForm">
                    {% if request.args.get("search") %}
                    <input type="search" id="dt-search" class="form-control col-md-12 dt-search" placeholder="検索"
                        name="search" value="{{ request.args.get('search') }}" />
                    {% else %}
                    <input type="search" id="dt-search" class="form-control col-md-12 dt-search" placeholder="検索"
                        name="search" />
                    {% endif %}
                </form>
            </div>
            {% endif %}
            <ul class="navbar-nav">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link">{{ current_user.username }}</span>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('auth.logout') }}" class="nav-link">ログアウト</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">新規登録</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">ログイン</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- block contentをsection class="container"で囲む -->
    <section class="container">
        {% block content %}{% endblock %}
    </section>
</body>

</html>

apps/detector/templates/detector/index.html
{% extends "detector/base.html" %}
{% block content %}
<!-- 画像アップロード画面へのリンクを追加する -->
<div class="col-md-10 text-right dt-image-register-btn">
    <a href="{{ url_for('detector.upload_image') }}" class="btn btn-primary">画像新規登録</a>
</div>
<!-- 画像一覧を表示する -->
{% for user_image in user_images %}
<div class="card col-md-7 dt-image-content">
    <header class="d-flex justify-content-between">
        <div class="dt-image-username">{{ user_image.User.username }}</div>
            <!-- 削除ボタンのフォームを追加する -->
            <div class="p-2">
                <form action="{{ url_for('detector.delete_image', image_id= user_image.UserImage.id) }}" method="POST">
                    {{ delete_form.csrf_token }}
                    {% if current_user.id == user_image.User.id %}
                    {{ delete_form.submit(class="btn btn-danger") }}
                    {% else %}
                    {{ delete_form.submit(class="btn btn-danger", disabled="disabled") }}
                    {% endif %}
                </form>
            </div>
    </header>
    <section>
        <img src="{{ url_for('detector.image_file', filename=user_image.UserImage.image_path) }}" alt="アップロード画像" />
    </section>
</div>
{% endfor %}
{% endblock %}

apps/detector/templates/detector/upload.html
{% extends "detector/base.html" %}
{% block content %}
<div>
    <h4>画像新規登録</h4>
    <p>アップロードする画像を選択してください</p>
    <form action="{{ url_for('detector.upload_image') }}" method="post" enctype="multipart/form-data"
        novalidate="novalidate">
        {{ form.csrf_token }}
        <div>
            <label>
                <span> {{ form.image(class="form-control-file") }} </span>
            </label>
        </div>
        {% for error in form.image.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <hr />
        <div>
            <label> {{ form.submit(class="btn btn-primary") }} </label>
        </div>
    </form>
</div>
{% endblock %}